name: antares-mysql
services:
  db:
    container_name: mysql-8-antares
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: antares-test
      MYSQL_USER: antares
      MYSQL_PASSWORD: password
    volumes:
      - ./init-sql:/docker-entrypoint-initdb.d/:z

  ssh-tunnel:
    container_name: ssh-tunnel-mysql-antares
    image: linuxserver/openssh-server:latest
    environment:
      - TZ=Europe/Rome
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_NAME=tunnel
      - USER_PASSWORD=password
      - LOG_STDOUT=true
    ports:
      - "2222:2222"
    volumes:
      - ./ssh-config:/config/sshd:rw

networks:
  default:
    driver: bridge